### ISSUE TITLE
License

### ISSUE THREAD

**Issue by EastArctica** [trevarj/glasscord-nord#1]
Hi @trevarj,

I came across your repository a while back and had forked it to use for a Replugged port. However, I noticed that there is currently no license attributed to the repository.

Could you please add a license to the repository? This would clarify the terms under which the project can be used, modified, and shared by others.

Thank you for considering this request, and please let me know if you have any questions or concerns.

Best regards,
EastArctica

**Comment by trevarj** [comment]
Hi, thanks for letting me know! I will add a license now.

**Comment by trevarj** [comment]
Resolved in [4efcdbc](https://github.com/trevarj/glasscord-nord/commit/4efcdbcd51ae6f374a17aad31e9b2653df0e1d34)
